# Site settings
title: Tiny's Blog
description:
  一个正在日新月异的互联网行业中摸爬滚打的程序猿,在这里写下了一些蛊惑箴言...

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zhangtiny123.github.io" # the base hostname & protocol for your site

author:
  fullname: Zhang Tao
  googleplus: https://www.google.com
  github: zhangtiny123
  twitter: TinyZhang
#   disqus: your_disqus_username

google_analytics: 'UA-70086215-1'

# Build settings
markdown: kramdown